### ISSUE TITLE
textarea, how to handle linebreaks?

### ISSUE THREAD

**Issue by 1F47E** [charmbracelet/bubbletea#800]
Hi there!
I'm building chat TUI app where I have textarea as text input.

I'm stuck with 2 issues right now:

1. I can't distinguish line breaks in the message from tea.KeyEnter. For example when multiline text is pasted from clipboard to textarea. Is it possible somehow pre process text form textarea to remove line breaks so that tea.KeyEnter will be not triggered in Update?

2. I cant find key combination of shift + enter for the line break while entering text inside textarea. I'm using tab right now for that. Using keypress as string "shift+enter" doesn't work.
```go
		switch keypress := msg.String(); keypress {
		case "ctrl+enter":
			m.textarea.SetValue(m.textarea.Value() + "\n")
		}
```

I can go with multiline route
```go
ta.KeyMap.InsertNewline.SetEnabled(true)
```
But then still need a key to send a message like shift+enter or ctrl+enter

Please point me in the right direction if there is any. Thanks!

**Comment by milanglacier** [comment]
This should be fixed once this PR is merged: https://github.com/charmbracelet/bubbletea/pull/397

**Comment by meowgorithm** [comment]
In terms of shift+enter, keep in mind that the notion of 'enter' is pretty loaded for terminals for historic reasons. Because of that shift+enter isn't possible by keyboard standards. There are a couple awesome and fairly well supported protocols we'd like to implement to allow for some form of support for this (see #869), however if your goal is to support shift+enter across the board I'd tread carefully.

**Comment by meowgorithm** [comment]
Hi! #397 is in the process of being merged, however we don't have an ETA yet. A proper bracketed paste solution is nuanced and will require additional work beyond the PR.

**Comment by meowgorithm** [comment]
Hi! Bubble Tea supports bracketed paste as of v0.26.0. If you’re still having trouble here please reopen the issue. Thanks!

**Comment by cherrot** [comment]
> I can go with multiline route
> 
> ta.KeyMap.InsertNewline.SetEnabled(true)
> But then still need a key to send a message like shift+enter or ctrl+enter
>
> Please point me in the right direction if there is any. Thanks!

It seems I still can't use `Shift+Enter` or `Ctrl+Enter` to send messages while using Enter to create a new line (or vice versa)?

**Comment by cherrot** [comment]
aha, #927 has explained this :D  maybe `Ctrl+S` is a good alternative
